update

diff --git a/home/bin/rofi-wifi b/home/bin/rofi-wifi
--- a/home/bin/rofi-wifi
+++ b/home/bin/rofi-wifi
@@ -4,87 +4,87 @@
 flag=$(cat /sys/class/net/wl*/flags)
 
 if [ "$flag" = "0x1003" ]; then
-	power="On"
+	power="直"
 else
-	power="Off"
+	power="睊"
 fi
 
 # Connection Status
 state=$(cat /sys/class/net/wl*/operstate)
 
 if [ "$state" = "up" ]; then
-	status=$(nmcli | grep "^wl" | sed 's/\ connected\ to/Connected to/' | cut -d ':' -f2)
+	status=$(LC_ALL=es_ES nmcli | grep "^wl" | sed 's/\ connected\ to//' | cut -d ':' -f2)
 else
-	status="Disconnected"
+	status="---"
 fi
-
-powertoggle=$( [ "$flag" = "0x1003" ] && echo "Power Off" || echo "Power On" )
 
 powerswitch() {
-if [ "$powertoggle" = "Power Off" ]; then
-	nmcli radio wifi off
-elif [ "$powertoggle" = "Power On" ]; then
-	nmcli radio wifi on
-fi
+    [ "$flag" = "0x1003" ] && nmcli radio wifi off || nmcli radio wifi on
 }
 
 connections() {
 list=$(nmcli --fields "SECURITY,SSID" device wifi list | tail -n +2 | sed "s/  */ /g" | sed -E "s/WPA*.?//g" | sed "s/^--//g" | sed "s/ //g")
-networks=$(printf "$list" | rofi -dmenu -i -hover-select -p "Select Wifi Network
-$status")
+networks=$(printf "$list" | rofi -config $HOME/.cache/wal/colors-rofi-wifi-connections-light.rasi -dmenu -i -hover-select -p "Select Wifi Network")
 wifi=$( echo "$networks" | sed "s/ //g" | sed "s/ //g" | xargs)
 [ -z "$networks" ] && exit
-nopass="No Password"
-pass=$(printf "$nopass\nCancel" | rofi -dmenu -i -hover-select -password -p "Wifi Password")
 
-if [ "$pass" = "" ]; then
-  exit
-elif [ "$pass" = "$nopass" ]; then
-  nmcli dev wifi con "$wifi" && printf "exit" | rofi -dmenu -only-match -i -p "Successfully Connected to $wifi" && exit
-elif [ "$pass" = "Cancel" ]; then
-  exit
+enterpass="Enter Password"
+nopass="No Password"
+needpass=$(printf "$enterpass\n$nopass\nCancel" | rofi -config $HOME/.cache/wal/colors-rofi-wifi-need-password-light.rasi -dmenu -i -hover-select)
+
+if [ "$needpass" = "" ]; then
+    exit
+elif [ "$needpass" = "$enterpass" ]; then
+    pass=$(rofi -config $HOME/.cache/wal/colors-rofi-wifi-password-light.rasi -dmenu -password -p "Enter Wifi Password")
+    [ "$pass" = "" ] && exit || nmcli dev wifi con "$wifi" password "$pass" && notify-send "Successfully Connected to $wifi" && exit
+elif [ "$needpass" = "$nopass" ]; then
+    nmcli dev wifi con "$wifi" && notify-send "Successfully Connected to $wifi" && exit
+elif [ "$needpass" = "Cancel" ]; then
+    exit
 else
-  nmcli dev wifi con "$wifi" password "$pass" &&  printf "exit" | rofi -dmenu -i -only-match -p "Successfully Connected to $wifi" && exit
+    exit
 fi
 
-printf "exit" | rofi -dmenu -i -p -only-match "Failed to Connect $wifi" && exit
+printf "exit" | rofi -config $HOME/.cache/wal/colors-rofi-wifi-light.rasi -dmenu -i -p -only-match "Failed to Connect $wifi" && exit
 }
 
 manual() {
 
-wifi=$(rofi -dmenu -i -p "Enter Wifi Name")
+wifi=$(rofi -config $HOME/.cache/wal/colors-rofi-wifi-light.rasi -dmenu -i -p "Enter Wifi Name")
 
 [ -z "$wifi" ] && exit
 nopass="Run Without Password"
-pass=$(printf "$nopass\nCancel" | rofi -dmenu -i -password -p "Wifi Password")
+pass=$(printf "$nopass\nCancel" | rofi -config $HOME/.cache/wal/colors-rofi-wifi-light.rasi -dmenu -i -password -p "Wifi Password")
 
 if [ "$pass" = "" ]; then
   exit
 elif [ "$pass" = "$nopass" ]; then
-  nmcli dev wifi con "$wifi" && printf "exit" | rofi -dmenu -i -only-match -p "Successfully Connected to $wifi" && exit
+  nmcli dev wifi con "$wifi" && printf "exit" | rofi -config $HOME/.cache/wal/colors-rofi-wifi-light.rasi -dmenu -i -only-match -p "Successfully Connected to $wifi" && exit
 elif [ "$pass" = "Cancel" ]; then
   exit
 else
-  nmcli dev wifi con "$wifi" password "$pass" &&  printf "exit" | rofi -dmenu -i -only-match -p "Successfully Connected to $wifi" && exit
+  nmcli dev wifi con "$wifi" password "$pass" &&  printf "exit" | rofi -config $HOME/.cache/wal/colors-rofi-wifi-light.rasi -dmenu -i -only-match -p "Successfully Connected to $wifi" && exit
 fi
 
-printf "exit" | rofi -dmenu -only-match -i -p "Failed to Connect $wifi" && exit
+printf "exit" | rofi -config $HOME/.cache/wal/colors-rofi-wifi-light.rasi -dmenu -only-match -i -p "Failed to Connect $wifi" && exit
 }
 
-options="$powertoggle\nConnections\nConnect Manually"
+powertoggleoption=$([ "$flag" = "0x1003" ] && echo "﨡" || echo "蘒")
+connectionsoption=$(echo "")
+configoption=$(echo "")
+options="$powertoggleoption\n$connectionsoption\n$configoption"
 
-rofiwifi=$(printf "$options" | rofi -dmenu -i -hover-select -p "Wifi
-Powered: $power
-Status: $status")
+rofiwifi=$(printf "$options" | rofi -config $HOME/.cache/wal/colors-rofi-wifi-light.rasi -dmenu -i -hover-select -p "
+$power $status")
 
 case $rofiwifi in
-	$powertoggle)
+	$powertoggleoption)
 		powerswitch
 	;;
-	Connections)
+	$connectionsoption)
     notify-send "Scanning"
 		connections
 	;;
-	"Connect Manually")
+        $configoption)
 		manual
 esac 2>/dev/null
